/* ============================================================
   NovaClass — Полная логика
   ============================================================ */

// === Данные аккаунта ===
const ALLOWED_USER = {
    name: 'МаксимТестер',
    login: 'maksim37@nova.class',
    password: 'maks37'
};

// === Переводы ===
const i18n = {
    ru: {
        login_subtitle:'Войдите в свой аккаунт',login_remember:'Запомнить меня',login_btn:'Войти',
        err_name_empty:'Введите логин',err_pass_empty:'Введите пароль',err_invalid:'Неверный логин или пароль',
        login_success:'Добро пожаловать',
        nav_home:'Главная',nav_schedule:'Расписание',nav_hw:'Домашние задания',nav_diary:'Дневник',nav_grades:'Оценки',
        profile_name:'Пользователь',profile_role:'Ученик',
        pd_settings:'Настройки',pd_theme:'Тема оформления',pd_help:'Помощь',pd_logout:'Выйти',
        hero_title:'Добро пожаловать!',
        events_title:'Ближайшие события',events_empty:'Событий пока нет',
        schedule_title:'Расписание',schedule_empty:'Расписание пока не добавлено',
        hw_title:'Домашние задания',hw_empty:'Заданий пока нет',
        diary_title:'Дневник',diary_text:'Раздел находится в разработке.',
        grades_title:'Оценки',grades_subtitle:'Оценки за поведение',grades_avg_label:'Средний балл',grades_empty:'Оценок пока нет',
        set_general:'Общие',set_notif:'Уведомления',set_sound:'Звук',
        set_display:'Отображение',set_font:'Размер шрифта',set_small:'Мелкий',set_medium:'Средний',set_large:'Крупный',set_compact:'Компактный режим',
        set_data:'Данные',set_clear:'Очистить кэш',
        faq1_q:'Как посмотреть расписание?',faq1_a:'Перейдите в раздел «Расписание» в боковом меню.',
        faq2_q:'Где находятся домашние задания?',faq2_a:'Откройте раздел «Домашние задания».',
        faq3_q:'Как сменить язык интерфейса?',faq3_a:'Нажмите на кнопку с языком (RU/EN/KZ) в правом верхнем углу.',
        faq4_q:'Как включить тёмную тему?',faq4_a:'Нажмите на профиль и выберите «Тема оформления».',
        faq5_q:'Кому написать за поддержкой?',faq5_a:'Обратитесь к классному руководителю.',
        logout_title:'Выход',logout_text:'Вы действительно хотите выйти из аккаунта?',logout_cancel:'Отмена',logout_confirm:'Выйти',
        logout_bye:'До свидания!',logout_bye_text:'Вы успешно вышли из системы',logout_back:'Войти снова',
        toast_notif_on:'Уведомления включены',toast_notif_off:'Уведомления отключены',
        toast_sound_on:'Звук включён',toast_sound_off:'Звук отключён',
        toast_compact_on:'Компактный режим включён',toast_compact_off:'Компактный режим отключён',
        toast_cache:'Кэш очищен',toast_theme_light:'Светлая тема',toast_theme_dark:'Тёмная тема',
        mon:'Пн',tue:'Вт',wed:'Ср',thu:'Чт',fri:'Пт',
        jan:'янв',feb:'фев',mar:'мар',apr:'апр',may:'мая',jun:'июн',jul:'июл',aug:'авг',sep:'сен',oct:'окт',nov:'ноя',dec:'дек',
    },
    en: {
        login_subtitle:'Sign in to your account',login_remember:'Remember me',login_btn:'Sign in',
        err_name_empty:'Enter login',err_pass_empty:'Enter password',err_invalid:'Invalid login or password',
        login_success:'Welcome',
        nav_home:'Home',nav_schedule:'Schedule',nav_hw:'Homework',nav_diary:'Diary',nav_grades:'Grades',
        profile_name:'User',profile_role:'Student',
        pd_settings:'Settings',pd_theme:'Appearance',pd_help:'Help',pd_logout:'Log out',
        hero_title:'Welcome!',
        events_title:'Upcoming Events',events_empty:'No events yet',
        schedule_title:'Schedule',schedule_empty:'No schedule yet',
        hw_title:'Homework',hw_empty:'No assignments yet',
        diary_title:'Diary',diary_text:'This section is under development.',
        grades_title:'Grades',grades_subtitle:'Behavior grades',grades_avg_label:'Average score',grades_empty:'No grades yet',
        set_general:'General',set_notif:'Notifications',set_sound:'Sound',
        set_display:'Display',set_font:'Font size',set_small:'Small',set_medium:'Medium',set_large:'Large',set_compact:'Compact mode',
        set_data:'Data',set_clear:'Clear cache',
        faq1_q:'How to view schedule?',faq1_a:'Go to "Schedule" in the sidebar.',
        faq2_q:'Where is homework?',faq2_a:'Open "Homework" section.',
        faq3_q:'How to change language?',faq3_a:'Click the language button (RU/EN/KZ) in the top right.',
        faq4_q:'How to enable dark theme?',faq4_a:'Click profile and select "Appearance".',
        faq5_q:'Who to contact for support?',faq5_a:'Contact your class teacher.',
        logout_title:'Log out',logout_text:'Are you sure you want to log out?',logout_cancel:'Cancel',logout_confirm:'Log out',
        logout_bye:'Goodbye!',logout_bye_text:'You have been logged out',logout_back:'Log in again',
        toast_notif_on:'Notifications on',toast_notif_off:'Notifications off',
        toast_sound_on:'Sound on',toast_sound_off:'Sound off',
        toast_compact_on:'Compact mode on',toast_compact_off:'Compact mode off',
        toast_cache:'Cache cleared',toast_theme_light:'Light theme',toast_theme_dark:'Dark theme',
        mon:'Mon',tue:'Tue',wed:'Wed',thu:'Thu',fri:'Fri',
        jan:'Jan',feb:'Feb',mar:'Mar',apr:'Apr',may:'May',jun:'Jun',jul:'Jul',aug:'Aug',sep:'Sep',oct:'Oct',nov:'Nov',dec:'Dec',
    },
    kz: {
        login_subtitle:'Тіркелгіңізге кіріңіз',login_remember:'Мені еске ал',login_btn:'Кіру',
        err_name_empty:'Логінді енгізіңіз',err_pass_empty:'Құпиясөзді енгізіңіз',err_invalid:'Логин немесе құпиясөз қате',
        login_success:'Қош келдіңіз',
        nav_home:'Басты бет',nav_schedule:'Кесте',nav_hw:'Үй тапсырмасы',nav_diary:'Күнделік',nav_grades:'Бағалар',
        profile_name:'Пайдаланушы',profile_role:'Оқушы',
        pd_settings:'Баптаулар',pd_theme:'Безендіру',pd_help:'Көмек',pd_logout:'Шығу',
        hero_title:'Қош келдіңіз!',
        events_title:'Жақын оқиғалар',events_empty:'Оқиғалар жоқ',
        schedule_title:'Кесте',schedule_empty:'Кесте жоқ',
        hw_title:'Үй тапсырмасы',hw_empty:'Тапсырмалар жоқ',
        diary_title:'Күнделік',diary_text:'Бөлім әзірленуде.',
        grades_title:'Бағалар',grades_subtitle:'Мінез-құлық бағалары',grades_avg_label:'Орташа балл',grades_empty:'Бағалар жоқ',
        set_general:'Жалпы',set_notif:'Хабарландырулар',set_sound:'Дыбыс',
        set_display:'Көрсету',set_font:'Шрифт өлшемі',set_small:'Кіші',set_medium:'Орташа',set_large:'Үлкен',set_compact:'Компактты режим',
        set_data:'Деректер',set_clear:'Кэшті тазарту',
        faq1_q:'Кестені қалай көруге болады?',faq1_a:'«Кесте» бөліміне өтіңіз.',
        faq2_q:'Үй тапсырмалары қайда?',faq2_a:'«Үй тапсырмасы» бөлімін ашыңыз.',
        faq3_q:'Тілді қалай ауыстыруға болады?',faq3_a:'Жоғарғы оң жақтағы тіл батырмасын басыңыз.',
        faq4_q:'Қараңғы теманы қалай қосуға болады?',faq4_a:'Профильді басып, «Безендіру» таңдаңыз.',
        faq5_q:'Көмекке кімге жүгінуге болады?',faq5_a:'Сынып жетекшісіне жүгініңіз.',
        logout_title:'Шығу',logout_text:'Шығуды растайсыз ба?',logout_cancel:'Болдырмау',logout_confirm:'Шығу',
        logout_bye:'Сау болыңыз!',logout_bye_text:'Жүйеден шықтыңыз',logout_back:'Қайта кіру',
        toast_notif_on:'Хабарландырулар қосылды',toast_notif_off:'Хабарландырулар өшірілді',
        toast_sound_on:'Дыбыс қосылды',toast_sound_off:'Дыбыс өшірілді',
        toast_compact_on:'Компактты режим қосылды
